spring:
  cloud:
    config:
      server:
#        native:
#          search-locations: classpath:/config #1
        git:
          uri: http://192.168.1.201/lirh/config-pro.git
          username: lirh
          password: 12345678


server:
  port: 8888
