server:
  port: 8762

eureka:
  instance:
    hostname: peer2
    leaseRenewalIntervalInSeconds: 3
  client:
    serviceUrl:
        defaultZone: http://${eureka.host:peer1}:${eureka.port:8761}/eureka/ #5
        peer3: http://${eureka.host:peer3}:${eureka.port:8763}/eureka/
  server:
     waitTimeInMsWhenSyncEmpty: 0
#    register-with-eureka: false
#    fetch-registry: false
